nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["*"] # Add your frontend origin here
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/": # Only for API paths
      allow_origin: ["*"] # Add your frontend origin here
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
